version: "3.9"

services:
  influxdb:
    container_name: influx_lesson
    image: influxdb:latest
    hostname: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin12345
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=super_secret_token
      - DOCKER_INFLUXDB_INIT_ORG=my_org
      - DOCKER_INFLUXDB_INIT_BUCKET=first_bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
    healthcheck:
      test: "curl -f http://localhost:8086/health || exit 1"
      interval: 5s
      timeout: 10s
      retries: 5